### ISSUE TITLE
Pipeline Node usage unclear

### ISSUE THREAD

**Issue by jcobol** [ShravanSunder/rivet-utilities-plugin#5]
I am trying to figure out what the Pipeline node wants for input.  I've tried many variations, but this one seems to match what the documentation says:
```
{
    "type": "object",
    "value": {
        "type": "object",
        "value": {
            "input_value": {
                "type": "string",
                "value": "hello world"
            }
        }
    }
}
```

However, I get "Error: Expected value of type number but got undefined".

An example project or object definition would really help.

**Comment by ShravanSunder** [comment]
i have a set of test graphs i'll split that out into an project when i get the time this week!

**Comment by ShravanSunder** [comment]
@jcobol until then. fyi from the readme 

in your pipeline graph you need to to have a graphInput node `pipelineInput`. This will have your input.  its available to any nodes in the pipeline process.  

![2024-05-11 0522 Code README md — rivet-utilities-plugin-latest — TS  JS  Node  Deno](https://github.com/ShravanSunder/rivet-utilities-plugin/assets/5294949/135328db-0e80-4f15-9bf4-e26f9aff3f82)

**Comment by jcobol** [comment]
I made sure I have a `pipelineInput` graph input node on the stage0 graph (the only graph I have connected right now) as well as an `input1` graph input node.

Here's an example of the Object node I tried to pass to the `Pipeline Input` node on the Pipeline node:
```
{
  "type": "object",
  "value": {
    "input1": {
      "type": "string",
      "value": "hello world"
    }
  }
}
```
I'm getting this error:
`Error: Expected value of type number but got undefined`

Console output:
```
remote: Node Pipeline Node (rl72n8Ds4Od_al8JkUte2-XJiTnVX9zLeEcZO2v3RHL) errored: Error: Expected value of type number but got undefined
    at Object.coerceType (C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:63554:11)
    at Object.process (file:///C:/Users/Civta/AppData/Local/com.ironcladapp.rivet/plugins/rivet-utilities-plugin-latest/package/dist/bundle.js:13465:19)
    at async #processNodeWithInputData (C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:79227:21)
    at async #processNormalNode (C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:79062:28)
    at async #processNode (C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:78917:7)
    at async #processNodeIfAllInputsAvailable (C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:78800:23)
    at async C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:78884:9
    at async C:\snapshot\rivet\packages\app-executor\bin\executor-bundle.cjs:67179:26
index-DX_vkOMZ.js:2988 remote: Finished processing node Pipeline Node (rl72n8Ds4Od_al8JkUte2)
index-DX_vkOMZ.js:2988 
 Error: Graph Main (o_cnowPqWF8MzUcv80NuI) failed to process due to errors in nodes: Pipeline Node (rl72n8Ds4Od_al8JkUte2): Error: Expected value of type number but got undefined
M	@	index-DX_vkOMZ.js:2988
```
